FROM node:18-slim

WORKDIR /app
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

# Yarn 1 как у тебя в проекте
RUN npm i -g yarn@1.22.22 --force
ENV YARN_CACHE_FOLDER=/tmp/.yarn-cache

# 1) сначала зависимости (кеш)
COPY package.json yarn.lock ./
RUN yarn config set registry https://registry.npmjs.org \
 && yarn config set network-timeout 600000 \
 && yarn install --frozen-lockfile --non-interactive

# 2) потом код (не ломает кеш deps при правках)
COPY . .

EXPOSE 3042
CMD ["yarn", "dev"]
